### ISSUE TITLE
Couple Errors 1.3-eggdrop-1.8 Might be overlooking something..

### ISSUE THREAD

**Issue by iiiper** [florian-sander/stats.mod#11]
Seems as if it is confusing itself. Sadly don't have ipv6 running as of yet. Hopefully in the near future.
Following error has to do with stats as it is fine without stats. Although it works decently It just seems to have some bugs. Sadly I deleted what I partially fixed a month ago. Just forget everything I did. Have not been able to fix the variable as of yet. running egg 1.8.4 on a private net.

no longer listening for livestats connections on port 8033
Tcl error in script for 'livestats-hack-start':
can't read "my-hostname": no such variable
WARNING: You are using the DEPRECATED variable 'my-ip' in your config file.
    To prevent future incompatibility, please use the vhost4/listen-addr variables instead.
    More information on this subject can be found in the eggdrop/doc/IPV6 file, or
    in the comments above those settings in the example eggdrop.conf that is included with Eggdrop.
WARNING: You are using the DEPRECATED variable 'my-ip' in your config file.
    To prevent future incompatibility, please use the vhost4/listen-addr variables instead.
    More information on this subject can be found in the eggdrop/doc/IPV6 file, or
    in the comments above those settings in the example eggdrop.conf that is included with Eggdrop.
Tcl error in script for 'livestats-hack-end':
can't read "my-hostname-livestats-backup": no such variable
Now listening for livestats connections on port 8033

I do apologize for not knowing more about this. I have not used a eggdrop in about 8years now.
Trying to get the hang of the changes & get back to learning more.
Just need a little direction to get this going without errors hopefully. 

TIA (all info & assistance is truly appreciated even if it makes me look dumb haha)

**Comment by wilkowy** [comment]
I have the same issue in eggdrop 1.8.4 (probably in whole 1.8.x, but jumped from 1.6.21 to 1.8.4).

You might add a correct `set my-ip "..."` and `set my-hostname "..."` in your config fille as a temporary fix to suppress error messages while rehashing. However while rehashing you will get 4 instead of 2 warnings. I have not tested if livestats work this way or not as I use static files.

**Comment by iiiper** [comment]
Ya it makes no difference on it. Both ways work. But I prefer 2 error messages over 4.

**Comment by wilkowy** [comment]
Of course it does a difference. You get 4 warnings instead of **2 errors** + 2 warnings, also setting those variables will most likely allow livestats to work again. It seems you have overlooked this part:
```
Tcl error in script for 'livestats-hack-start':
can't read "my-hostname": no such variable
```

**Comment by iiiper** [comment]
Oh I understand it. But it currently works. I have no issues with it working.
I'm using ipv6 and ipv4 and it has pulled up stats on both.

Even when I add that to my conf etc it still gives the errors. Unless I missed something. 

Currently I have given up on fixing it as I feel the project is dead.

**Comment by wilkowy** [comment]
So why are you closing an unfixed issue?
